Staff management/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import admin, account, main, subpage1, lun, Ingre, home, category, favorite
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # Main page
    path('main/', main.home),

    path('meun/main/add/', main.main_menu_add),

    # home pages
    path('meun/<int:nid>/det/', home.meun_list),
    # path('meun/det1/', home.meun_list_cal),


    # Second menu

    path('meun/add/', main.add_meun),
    path('meun/<int:nid>/edit/', main.edit_meun),


    # my favorite

    path('meun/<int:nid>/list/', favorite.fav_meun),
    path('meun/<int:nid>/list2/', favorite.fav_cook),

    path('meun/list/', favorite.fav_list),
    path('meun/<int:nid>/delete/', favorite.fav_dele),


    # Subpage1
    path('subpage1/', subpage1.page),
    path('subpage2/', subpage1.page2),
    path('subpage3/', subpage1.page3),
    path('subpage4/', subpage1.page4),
    path('subpage5/', subpage1.page5),
    path('subpage6/', subpage1.page6),
    path('subpage7/', subpage1.page7),
    path('subpage8/', subpage1.page8),
    path('subpage9/', subpage1.page9),
    path('subpage10/', subpage1.page10),
    path('subpage11/', subpage1.page11),
    path('subpage12/', subpage1.page12),
    path('subpage13/', subpage1.page13),
    path('subpage14/', subpage1.page14),


    # Ingredient
    path('Ingredientm/', Ingre.meat),
    path('Ingredientm/add/', Ingre.madd),
    path('Ingredientv/', Ingre.veg),
    path('Ingredientv/add/', Ingre.vadd),
    path('Ingredienta/', Ingre.aux),
    path('Ingredienta/add/', Ingre.aadd),


    # Category
    path('category/list/', category.page),

    # lun bo figure
    path('det_lun1/', lun.page1),
    path('det_lun2/', lun.page2),
    path('det_lun3/', lun.page3),

    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # register
    path('register/', account.regist),

    # personal profile
    path('person/list', account.person)

]

app01/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="Username", max_length=32)
    password = models.CharField(verbose_name="Password", max_length=64)

    def __str__(self):
        return self.username


class Menu(models.Model):
    """ all meun """
    name = models.CharField(verbose_name="Name", max_length=32)
    time = models.IntegerField(verbose_name="time need to be done")

    tem = models.IntegerField(verbose_name="temperature")
    inter = models.CharField(verbose_name="materials needed", max_length=256)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/')


class meat(models.Model):
    """ The ingredients """
    meat = models.CharField(verbose_name="Meat", max_length=16, default="Beef")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.meat


class Auxiliary(models.Model):
    """ The ingredients """
    aux = models.CharField(verbose_name="aux", max_length=16, default="Salt")

    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.aux


class vegetable(models.Model):
    """ The ingredients """
    veg = models.CharField(verbose_name="vegetable", max_length=16, default="coriander")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.veg


class home(models.Model):
    """ The data in home page"""

    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')


class favorite(models.Model):
    """ The data in home page"""
    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')

app01/views/Ingre.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

""" for meat """


class MainMenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.meat
        fields = "__all__"


def meat(request):
    queryset = models.meat.objects.all()

    return render(request, 'Ingrem.html', {"queryset": queryset})


def madd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredientm/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


""" for vegetable """


class MainMenuModelForm_veg(BootStrapModelForm):
    class Meta:
        model = models.vegetable
        fields = "__all__"


def veg(request):
    queryset = models.vegetable.objects.all()

    return render(request, 'Ingrev.html', {"queryset": queryset})


def vadd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm_veg()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm_veg(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredientv/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


""" for Auxiliary"""


class MainMenuModelForm_aux(BootStrapModelForm):
    class Meta:
        model = models.Auxiliary
        fields = "__all__"


def aux(request):
    queryset = models.Auxiliary.objects.all()

    return render(request, 'Ingrea.html', {"queryset": queryset})


def aadd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm_aux()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm_aux(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredienta/')
    return render(request, 'upload_form.html', {"form": form, "title": title})

app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms
from app01.models import Admin
from app01 import models
from app01.utils.bootstrap import BootStrapForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code
from io import BytesIO
from app01.utils.bootstrap import BootStrapModelForm
from django.core.exceptions import ValidationError


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(render_value=True),
        required=True,
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True),

        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("The password is different")
        # 返回什么，此字段以后保存到数据库就是什么。
        return confirm


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="Verification code",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def regist(request):
    title = "Register your account"
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'regist.html', {"form": form, "title": title})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect("/login/")

    return render(request, 'regist.html', {"form": form, "title": title})


def login(request):
    """ Login """

    form = LoginForm(data=request.POST)
    if form.is_valid():

        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "Verification code is wrong")
            return render(request, 'login.html', {"form": form})

        # admin_object = models.Admin.objects.filter(username=form.cleaned_data["username"], password=form.cleaned_data["password"]).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "Username or password is wrong!")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {"form": form})

        request.session["info"] = {"id": admin_object.id, "name": admin_object.username}
        # session 可以保存7天， 7天之内不需要登录。7 天之后 session失效，要重新登录。
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect('/main/')

    return render(request, 'login.html', {"form": form})


def image_code(request):
    """ Generate vertification code """
    # 调用含pillow函数的文件,生成图片
    img, code_string = check_code()

    # print(code_string)
    # 写入到自己的cookie中，以便后续中获取验证码在进行校验
    request.session['image_code'] = code_string
    # 给Session设置一个60秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    stream.getvalue()

    return HttpResponse(stream.getvalue())


def logout(request):
    """ Logout """
    request.session.clear()

    return redirect('/login/')


def person(request):
    return render(request, 'personal.html')

app01/views/category.py
from django.shortcuts import render
from app01 import models


def page(request):
    queryset = models.home.objects.all()
    return render(request, 'category.html', {"queryset": queryset})

app01/views/favorite.py
from django.http import HttpResponseRedirect

from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination
import tkinter.messagebox
from tkinter import *
from django.contrib import messages
from django.shortcuts import render, redirect
from app01 import models


# My favorite
def fav_meun(request, nid):
    """ Favorite Menu list """
    queryset = models.home.objects.filter(id=nid)
    for info in queryset:
        name = info.name
        tem = info.temperature
        time = info.time
        ute = info.utensils
        cate = info.cate
        des = info.description
        meat = info.meat
        au = info.auxiliary
        veg = info.veg
        step = info.steps
        rate = info.rate
        cal = info.calories
        img = info.img
        context = {
            "name": name,
            "temperature": tem,
            "time": time,
            "utensils": ute,
            "cate": cate,
            "description": des,
            "meat": meat,
            "auxiliary": au,
            "veg": veg,
            "steps": step,
            "rate": rate,
            "calories": cal,
            "img": img,
        }
        judge = models.favorite.objects.values_list('name', flat=True)

        if context['name'] in judge:
            messages.error(request, 'The data already exists')

            return HttpResponseRedirect('/main/')

        queryset1 = models.favorite.objects.create(**context)

        queryset2 = models.favorite.objects.all()

        return render(request, 'meun_list.html', {"queryset2": queryset2})


def fav_list(request):
    search_data = request.GET.get('q', "")

    queryset2 = models.favorite.objects.filter(name__icontains=search_data)
    if queryset2:
        page_object = Pagination(request, queryset2)
        context = {
            "search_data": search_data,
            "queryset2": page_object.page_queryset,
            "page_string": page_object.html(),
        }
        return render(request, 'meun_list.html', context)

    queryset2 = models.favorite.objects.filter(calories__icontains=search_data)

    page_object = Pagination(request, queryset2)
    context = {
        "search_data": search_data,
        "queryset2": page_object.page_queryset,
        "page_string": page_object.html(),
    }

    return render(request, 'meun_list.html', context)

    # queryset2 = models.favorite.objects.all()
    # return render(request, 'meun_list.html', {"queryset2": queryset2})


def fav_dele(request, nid):
    models.favorite.objects.filter(id=nid).delete()
    return redirect('/meun/list/')


def fav_cook(request, nid):
    queryset = models.favorite.objects.filter(id=nid)
    tools = int(request.POST.get("tools"))
    return render(request, 'sec_menu1.html', {"queryset": queryset, "tools": tools})

app01/views/home.py
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

from django.shortcuts import render, redirect, HttpResponse
from app01 import models


class MenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.home
        fields = "__all__"
        # exclude = ["id"]


def meun_list(request, nid):
    queryset = models.home.objects.filter(id=nid)
    tools = int(request.POST.get("tools"))
    print(tools)
    return render(request, 'sec_menu.html', {"queryset": queryset, "tools": tools})

app01/views/lun.py
from django.shortcuts import render


def page1(request):
    return render(request, 'det_lun1.html')


def page2(request):
    return render(request, 'det_lun2.html')


def page3(request):
    return render(request, 'det_lun3.html')

app01/templates/Ingrem.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .one {
            width: 100%;
            height: 400px;
            margin: 50px 0 30px 0;
            background-color: darkgrey;

        }

        .two {
            float: left;
            width: 200px;
            height: 100%;

        }

        .two h2 {
            text-align: center;
            margin-top: 150px;
        }


        .three ul {
            width: 804px;
            float: right;
            background: #fff;
            margin-bottom: -1px;
        }


        ol, ul {
            list-style: none;
        }

        * {
            margin: 0;
            padding: 0;
        }

        .three {
            margin-left: 1px;
            float: left;
        }

        .three a {
            float: left;
            height: 132px;
            line-height: 64px;
            width: 265px;
            border-left: 1px solid #eeeeee;
            border-bottom: 1px solid #eeeeee;
            font-size: 20px;
            color: #333;
            text-decoration: none;
            text-align: center;
            position: relative;
        }


	</style>


	<div class="container">

		<div class="one">
			<a href="/Ingredientm/add/" class="list-group-item list-group-item-danger">Create Meat</a>
			<div class="two">
				<h2>Meat</h2>
			</div>
			<div class="three">

				<ul>
					{% for obj in queryset %}
						<li><a title="The method of cooking" href="#" target="_blank">{{ obj.meat }}</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>


	</div>


{% endblock %}

app01/templates/Ingrev.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .one {
            width: 100%;
            height: 400px;
            margin: 50px 0 30px 0;
            background-color: lightgreen;

        }

        .two {
            float: left;
            width: 200px;
            height: 100%;

        }

        .two h2 {
            text-align: center;
            margin-top: 150px;
        }


        .three ul {
            width: 804px;
            float: right;
            background: #fff;
            margin-bottom: -1px;
        }


        ol, ul {
            list-style: none;
        }

        * {
            margin: 0;
            padding: 0;
        }

        .three {
            margin-left: 1px;
            float: left;
        }

        .three a {
            float: left;
            height: 132px;
            line-height: 64px;
            width: 265px;
            border-left: 1px solid #eeeeee;
            border-bottom: 1px solid #eeeeee;
            font-size: 20px;
            color: #333;
            text-decoration: none;
            text-align: center;
            position: relative;
        }


	</style>


	<div class="container">

		<div class="one">
			<a href="/Ingredientv/add/" class="list-group-item list-group-item-success">Create Vegetables</a>
			<div class="two">
				<h2>Meat</h2>
			</div>
			<div class="three">

				<ul>
					{% for obj in queryset %}
						<li><a title="The method of cooking" href="#" target="_blank">{{ obj.veg }}</a></li>
					{% endfor %}
				</ul>

			</div>
		</div>


	</div>


{% endblock %}

app01/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container">

		<div style="margin-bottom: 10px" class="clearfix">
			<a class="btn btn-success" href="/admin/add/">    {#target="_blank"#}
				<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
				Create new admin
			</a>

			<div style="float: right; width: 300px">
				<form method="get">
					<div class="input-group">

						<input type="text" name="q" class="form-control" placeholder="Keyword"
						       value="{{ search_data }}">
						<span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
	                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>

					</div>
				</form>
			</div>
		</div>
		<table class="table table-bordered">
			<caption>
				<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
				The list of admin
			</caption>
			<thead>
			<tr>
				<th>ID</th>
				<th>Username</th>
				<th>Password</th>
				<th>Reset password</th>
				<th>Operation</th>
			</tr>
			</thead>
			<tbody>
			{% for obj in queryset %}
				<tr>
					<td>{{ obj.id }}</td>
					<td>{{ obj.username }}</td>
					<td>*******</td>
					<td>
						<a href="/admin/{{ obj.id }}/reset/">Reset password</a>
					</td>
					<td>
						<a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">Edit</a>
						<a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">Delete</a>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<ul class="pagination">
			{{ page_string }}
		</ul>
	</div>
{% endblock %}

app01/templates/category.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .one {
            width: 100%;
            height: 400px;
            margin: 50px 0 30px 0;
            background-color: lightblue;

        }

        .two {
            float: left;
            width: 200px;
            height: 100%;

        }

        .two h2 {
            text-align: center;
            margin-top: 150px;
        }


        .three ul {
            width: 804px;
            float: right;
            background: #fff;
            margin-bottom: -1px;
        }


        ol, ul {
            list-style: none;
        }

        * {
            margin: 0;
            padding: 0;
        }

        .three {
            margin-left: 1px;
            float: left;
        }

        .three a {
            float: left;
            height: 132px;
            line-height: 64px;
            width: 265px;
            border-left: 1px solid #eeeeee;
            border-bottom: 1px solid #eeeeee;
            font-size: 20px;
            color: #333;
            text-decoration: none;
            text-align: center;
            position: relative;
        }


	</style>


	<div class="container">
		<div class="one">
			<div class="two">
				<h2>Meat class</h2>

			</div>
			<div class="three">
				<ul>
					{% for obj in queryset %}
						<li><a title="Meat" href="#" target="_blank">{{ obj.get_cate_display }}  </a></li>

					{% endfor %}
				</ul>
			</div>
		</div>


	</div>



{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container">
		<div class="alert alert-danger" role="alert">{{ msg }}</div>
	</div>

{% endblock %}

app01/templates/personal.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
		.col-md-6 h2{
			padding-top: 40px;
		}

	</style>
	<div class="container">
		<div class="row" style="margin-left: 150px">
			<div class="col-md-6" style="border: 1px solid purple; width: 400px; height: 600px">
				<img style="height: 400px; width: 400px; padding-right: 20px" src="{% static 'img/111.jpeg' %}">
			</div>
			<div class="col-md-6" style="border: 1px solid purple; width: 400px; height: 600px; margin-left: 20px">
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>




			</div>
		</div>


	</div>






{% endblock %}

app01/templates/regist1.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">{{ title }}</div>
			<div class="panel-body">
				<form method="post" novalidate>
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group" >
							<label>{{ field.label }}</label>
							{{ field }}
							<span style="color: red;">{{ field.errors.0 }}</span>

						</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

app01/templates/subpage1.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .panel-body {
            padding: 5px;
        }

        .panel-body img {
            width: 160px;
            height: 160px;
        }

        .text {
            float: right;
            padding-right: 500px;
        }
	</style>
	<div class="container">
		{% for obj in queryset %}
			<h1 style="color: #985f0d">{{ obj.get_cate_display}}</h1>
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title"><h3>{{ obj.name }}</h3></h3>
				</div>
				<div class="panel-body">
					<img src="/media/{{ obj.img }}">
					<div class="text">
						<h3>Description：{{ obj.description }}</h3>
						<h3>Score：{{ obj.get_rate_display }}</h3>
					</div>

				</div>
			</div>
		{% endfor %}

	</div>



{% endblock %}

app01/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

<div><p style=" "><a style=""
                                                   href="/meun/{{ obj.id }}/det/" class="btn btn-success"
                                                   role="button">Start!</a></p>
</div>

<div>
	<h5 style="   ">Quantity:<input
			style="width: 30px">
	</h5>
</div>
</body>
</html>

app01/templates/upload_list.html
{% extends 'layout.html' %}

{% block content %}

	<div class="container">
		<form method="post" enctype="multipart/form-data">
			<input type="text" name="username">
			<input type="file" name="avatar">
			<input type="submit" name="提交">
		</form>
	</div>

{% endblock %}